# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
import django.utils.timezone
import shopman.omniman.models.session
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True, verbose_name='código')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='nome')),
                ('listing_ref', models.CharField(blank=True, default='', help_text='Ref da Listing que serve como catálogo deste canal', max_length=50, verbose_name='listagem')),
                ('pricing_policy', models.CharField(choices=[('internal', 'interna'), ('external', 'externa')], default='internal', max_length=16, verbose_name='política de preço')),
                ('edit_policy', models.CharField(choices=[('open', 'aberta'), ('locked', 'bloqueada')], default='open', max_length=16, verbose_name='política de edição')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordem de exibição')),
                ('config', models.JSONField(blank=True, default=dict, help_text='ChannelConfig schema (7 aspectos). Chaves: confirmation {mode, timeout_minutes}, payment {method, timeout_minutes}, stock {hold_ttl_minutes, safety_margin, planned_hold_ttl_hours}, pipeline {on_commit, on_confirmed, on_cancelled, ...} (listas de topics), notifications {backend, fallback, routing}, rules {validators, modifiers, checks}, flow {transitions, terminal_statuses, auto_transitions, auto_sync_fulfillment}. Use presets: pos(), remote(), marketplace().', verbose_name='configuração')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'canal',
                'verbose_name_plural': 'canais',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=64, verbose_name='tópico')),
                ('status', models.CharField(choices=[('queued', 'em fila'), ('running', 'em execução'), ('done', 'concluído'), ('failed', 'falhou')], db_index=True, default='queued', max_length=16, verbose_name='status')),
                ('payload', models.JSONField(blank=True, default=dict, encoder=shopman.omniman.models.session.DecimalEncoder, help_text='Dados da tarefa. Schema depende do topic. Ex: stock.hold → {"sku": "PAO-FRANCES", "qty": 10}', verbose_name='payload')),
                ('attempts', models.IntegerField(default=0, verbose_name='tentativas')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='disponível em')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='último erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'diretiva',
                'verbose_name_plural': 'diretivas',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64, verbose_name='escopo')),
                ('key', models.CharField(max_length=128, verbose_name='chave')),
                ('status', models.CharField(choices=[('in_progress', 'em andamento'), ('done', 'concluído'), ('failed', 'falhou')], default='in_progress', max_length=16, verbose_name='status')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='código de resposta')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='corpo da resposta')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'chave de idempotência',
                'verbose_name_plural': 'chaves de idempotência',
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='omniman_uniq_idempotency_scope_key')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True, verbose_name='referência')),
                ('session_key', models.CharField(db_index=True, default='', max_length=64, verbose_name='chave da sessão')),
                ('handle_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='tipo de identificação')),
                ('handle_ref', models.CharField(blank=True, max_length=64, null=True, verbose_name='identificador')),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='referência externa')),
                ('status', models.CharField(choices=[('new', 'novo'), ('confirmed', 'confirmado'), ('processing', 'em preparo'), ('ready', 'pronto'), ('dispatched', 'despachado'), ('delivered', 'entregue'), ('completed', 'concluído'), ('cancelled', 'cancelado'), ('returned', 'devolvido')], db_index=True, default='new', max_length=32, verbose_name='status')),
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=shopman.omniman.models.session.DecimalEncoder, help_text='Snapshot selado do pedido no momento da criação. Não editar manualmente.', verbose_name='snapshot')),
                ('data', models.JSONField(blank=True, default=dict, encoder=shopman.omniman.models.session.DecimalEncoder, help_text='Dados extras do pedido. Formato livre. Ex: {"notes": "Sem cebola", "delivery_address": "Rua X, 123"}', verbose_name='dados extras')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='moeda')),
                ('total_q', models.BigIntegerField(default=0, verbose_name='total (q)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('processing_at', models.DateTimeField(blank=True, null=True, verbose_name='em preparo em')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='pronto em')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='despachado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='devolvido em')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniman.channel', verbose_name='canal de venda')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pendente'), ('in_progress', 'em andamento'), ('dispatched', 'despachado'), ('delivered', 'entregue'), ('cancelled', 'cancelado')], db_index=True, default='pending', max_length=32, verbose_name='status')),
                ('tracking_code', models.CharField(blank=True, default='', max_length=128, verbose_name='código de rastreio')),
                ('tracking_url', models.URLField(blank=True, default='', verbose_name='URL de rastreio')),
                ('carrier', models.CharField(blank=True, default='', max_length=64, verbose_name='transportadora')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Metadados de entrega. Ex: {"tracking_code": "BR123", "carrier": "correios"}', verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='despachado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='omniman.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'fulfillment',
                'verbose_name_plural': 'fulfillments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=64, verbose_name='ID da linha')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='nome')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('unit_price_q', models.BigIntegerField(verbose_name='preço unitário (q)')),
                ('line_total_q', models.BigIntegerField(verbose_name='total da linha (q)')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Metadados do item. Ex: {"customization": "sem gluten", "gift_wrap": true}', verbose_name='metadados')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='omniman.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='omniman.fulfillment', verbose_name='fulfillment')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='omniman.orderitem', verbose_name='item do pedido')),
            ],
            options={
                'verbose_name': 'item do fulfillment',
                'verbose_name_plural': 'itens do fulfillment',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, verbose_name='chave da sessão')),
                ('handle_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='tipo de identificação')),
                ('handle_ref', models.CharField(blank=True, max_length=64, null=True, verbose_name='identificador')),
                ('state', models.CharField(choices=[('open', 'aberta'), ('committed', 'fechada'), ('abandoned', 'abandonada')], db_index=True, default='open', max_length=16, verbose_name='status')),
                ('pricing_policy', models.CharField(choices=[('internal', 'interna'), ('external', 'externa')], default='internal', max_length=16, verbose_name='política de preço')),
                ('edit_policy', models.CharField(choices=[('open', 'aberta'), ('locked', 'bloqueada')], default='open', max_length=16, verbose_name='política de edição')),
                ('rev', models.IntegerField(db_index=True, default=0, verbose_name='revisão')),
                ('data', models.JSONField(default=dict, help_text='Dados da sessão (checks, validações). Populado automaticamente pelo sistema.', verbose_name='dados')),
                ('pricing', models.JSONField(blank=True, default=dict, help_text='Resultado da precificação. Populado automaticamente pelos modifiers.', verbose_name='precificação')),
                ('pricing_trace', models.JSONField(blank=True, default=list, help_text='Trace de auditoria dos modifiers. Populado automaticamente.', verbose_name='trace de precificação')),
                ('commit_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='token de commit')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='aberta em')),
                ('committed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniman.channel', verbose_name='canal de venda')),
            ],
            options={
                'verbose_name': 'sessão',
                'verbose_name_plural': 'sessões',
            },
            managers=[
                ('objects', shopman.omniman.models.session.SessionManager()),
            ],
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=64, verbose_name='ID da linha')),
                ('sku', models.CharField(blank=True, default='', max_length=64, verbose_name='SKU')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='nome')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('unit_price_q', models.BigIntegerField(default=0, verbose_name='preço unitário (q)')),
                ('line_total_q', models.BigIntegerField(default=0, verbose_name='total da linha (q)')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Metadados do item. Ex: {"customization": "extra queijo"}', verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_items', to='omniman.session', verbose_name='sessão')),
            ],
            options={
                'verbose_name': 'item da sessão',
                'verbose_name_plural': 'itens da sessão',
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='sequência')),
                ('type', models.CharField(db_index=True, max_length=64, verbose_name='tipo')),
                ('actor', models.CharField(max_length=128, verbose_name='ator')),
                ('payload', models.JSONField(default=dict, help_text='Dados do evento. Ex: {"new_status": "confirmed"} ou {"error": "motivo"}', verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='omniman.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'evento do pedido',
                'verbose_name_plural': 'eventos do pedido',
                'ordering': ('seq',),
                'constraints': [models.UniqueConstraint(fields=('order', 'seq'), name='omniman_uniq_order_event_seq')],
            },
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'line_id'), name='omniman_uniq_order_item_line_id'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='omniman_order_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='omniman_fulfillment_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('channel', 'session_key'), name='omniman_uniq_session_channel_key'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'open'), ('handle_type__isnull', False), ('handle_ref__isnull', False)), fields=('channel', 'handle_type', 'handle_ref'), name='omniman_uniq_open_session_handle'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.UniqueConstraint(fields=('session', 'line_id'), name='omniman_uniq_session_item_line_id'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='omniman_session_item_qty_positive'),
        ),
    ]
