# Generated by Django 5.2.12 on 2026-04-04 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_type', models.CharField(db_index=True, help_text='Slug do RefType (ex: POS_TABLE, ORDER_NUMBER)', max_length=32, verbose_name='tipo de referência')),
                ('target_kind', models.CharField(choices=[('SESSION', 'Session'), ('ORDER', 'Order')], help_text='Tipo do target associado', max_length=8, verbose_name='tipo de alvo')),
                ('target_id', models.UUIDField(db_index=True, help_text='ID do target (Session.id ou Order.id)', verbose_name='ID do alvo')),
                ('value', models.CharField(db_index=True, help_text="Valor normalizado do localizador (ex: '12', '001', 'ABC123')", max_length=64, verbose_name='valor')),
                ('scope', models.JSONField(default=dict, help_text="Scope de unicidade (ex: {store_id: 1, business_date: '2025-12-19'})", verbose_name='escopo')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Se False, Ref está desativada (não resolve)', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
                'indexes': [models.Index(fields=['ref_type', 'value', 'is_active'], name='omniman_refs_type_value_active_idx'), models.Index(fields=['target_kind', 'target_id', 'is_active'], name='omniman_refs_target_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='RefSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(db_index=True, help_text='Nome da sequência (geralmente o RefType.slug)', max_length=32, verbose_name='nome da sequência')),
                ('scope_hash', models.CharField(db_index=True, help_text='Hash do scope para particionamento', max_length=64, verbose_name='hash do escopo')),
                ('scope', models.JSONField(default=dict, help_text='Scope original (para debug/auditoria)', verbose_name='escopo')),
                ('last_value', models.PositiveIntegerField(default=0, help_text='Último valor gerado nesta sequência', verbose_name='último valor')),
            ],
            options={
                'verbose_name': 'Sequência de Referência',
                'verbose_name_plural': 'Sequências de Referência',
                'constraints': [models.UniqueConstraint(fields=('sequence_name', 'scope_hash'), name='unique_sequence_scope')],
            },
        ),
    ]
